### ISSUE TITLE
Feature request: support absence of controlling

### ISSUE THREAD

**Issue by cod3monk** [lnNgyn1/PeriodInsertBundle#3]
Hi @lnNgyn1,

thanks for the plugin in. It has saved us quite some time and improved the life of our volunteers :)

Would it be possible to also support adding absence entries provided with the [controlling extension](https://www.kimai.org/store/controlling.html)?

Thanks!

**Comment by lnNgyn1** [comment]
Hi, thanks for opening this issue! I am glad to hear that this little plugin has been helpful. Unfortunately, I do not have access to the code for that extension, so I am unable to support adding absence entries at this moment.
