### ISSUE TITLE
Authorization for block "Extended properties"

### ISSUE THREAD

**Issue by idemus** [lnNgyn1/PeriodInsertBundle#8]
Hi Alan,

would it be possible to add an authorization to the block "Extended properties".
My employees (the normal user) should not be able to set things like activity rates. That's all done central by project customization by a central person.

Best regards
Klaus

**Comment by lnNgyn1** [comment]
Hi, thanks for opening this issue! I believe this is already implemented by the plugin. The `Extended settings` block only shows up when either one of these permissions are set to `Yes`: `edit_billable_own_timesheet`, `edit_export_own_timesheet`, `edit_rate_own_timesheet`. When each of these permissions are set to `Yes`, the corresponding form item will show up under the `Extended settings` block. On a fresh Kimai setup, the default role settings have these three permissions set to `No` for the normal user, who will be unable to see the `Extended settings` block. Only if the user is set to either one of the roles `Teamlead`, `Administrator`, or `System-Admin` will they be able to see the `Extended settings` block. Try adjusting the permissions on your setup, and let me know if that addresses your issue!

**Comment by idemus** [comment]
I've checked it as you suggested it and it already works. Thank you! :)
